import 'package:flutter/material.dart';

class Student extends StatefulWidget {
  const Student({super.key});

  @override
  State<Student> createState() => _StudentState();
}

class _StudentState extends State<Student> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(appBar:AppBar(
      backgroundColor: Colors.black12,
      title: Center(child: Text("CHESS BOARD")),
    ),
      body:SafeArea(
        child: Row(mainAxisAlignment:MainAxisAlignment.center ,
          children: [
            Column(mainAxisAlignment:MainAxisAlignment.center ,
              children: [
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.black,
                ),Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                ), Container(
                  width: 50,
                  height: 50,
                  color: Colors.black,
                ),Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                ), Container(
                  width: 50,
                  height: 50,
                  color: Colors.black,
                ),Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                ), Container(
                  width: 50,
                  height: 50,
                  color: Colors.black,
                ),Container(
                  width: 50,
                  height: 50,
                  color: Colors.white,
                ),

              ],
            ),Column(mainAxisAlignment:MainAxisAlignment.center ,
              children: [
                Container(width: 50,
                  height: 50,
                  color: Colors.white,

                ),Container(width: 50,
                  height: 50,
                  color: Colors.black,

                ),Container(width: 50,
                  height: 50,
                  color: Colors.white,

                ),Container(width: 50,
                  height: 50,
                  color: Colors.black),
                Container(width: 50,
                  height: 50,
                  color: Colors.white,),
                Container(width: 50,
                    height: 50,
                    color: Colors.black),
                Container(width: 50,
                    height: 50,
                    color: Colors.white),
                Container(width: 50,
                    height: 50,
                    color: Colors.black),

              ],
            ),Column(mainAxisAlignment:MainAxisAlignment.center ,
              children: [
              Container(width: 50,
              height: 50,
              color: Colors.black,

            ),Container(width: 50,
              height: 50,
              color: Colors.white,

            ),Container(width: 50,
                height: 50,
                color: Colors.black),
              Container(width: 50,
                height: 50,
                color: Colors.white,),
              Container(width: 50,
                  height: 50,
                  color: Colors.black),
              Container(width: 50,
                  height: 50,
                  color: Colors.white),
              Container(width: 50,
                  height: 50,
                  color: Colors.black),
                Container(width: 50,
                    height: 50,
                    color: Colors.white),
              ],
            ),Column(mainAxisAlignment:MainAxisAlignment.center ,
              children: [
                Container(width: 50,
                  height: 50,
                  color: Colors.white,

                ),Container(width: 50,
                    height: 50,
                    color: Colors.black),
                Container(width: 50,
                  height: 50,
                  color: Colors.white,),
                Container(width: 50,
                    height: 50,
                    color: Colors.black),
                Container(width: 50,
                    height: 50,
                    color: Colors.white),
                Container(width: 50,
                    height: 50,
                    color: Colors.black),
                Container(width: 50,
                    height: 50,
                    color: Colors.white),
                Container(width: 50,
                    height: 50,
                    color: Colors.black),
              ],
            ),Column(mainAxisAlignment:MainAxisAlignment.center ,
              children: [
                Container(width: 50,
                  height: 50,
                  color: Colors.black,

                ),Container(width: 50,
                  height: 50,
                  color: Colors.white,

                ),Container(width: 50,
                    height: 50,
                    color: Colors.black),
                Container(width: 50,
                  height: 50,
                  color: Colors.white,),
                Container(width: 50,
                    height: 50,
                    color: Colors.black),
                Container(width: 50,
                    height: 50,
                    color: Colors.white),
                Container(width: 50,
                    height: 50,
                    color: Colors.black),
                Container(width: 50,
                    height: 50,
                    color: Colors.white),
              ],
            ),Column(mainAxisAlignment:MainAxisAlignment.center ,
              children: [

                Container(width: 50,
                  height: 50,
                  color: Colors.white,

                ),Container(width: 50,
                    height: 50,
                    color: Colors.black),
                Container(width: 50,
                  height: 50,
                  color: Colors.white,),
                Container(width: 50,
                    height: 50,
                    color: Colors.black),
                Container(width: 50,
                    height: 50,
                    color: Colors.white),
                Container(width: 50,
                    height: 50,
                    color: Colors.black),
                Container(width: 50,
                    height: 50,
                    color: Colors.white),
                Container(width: 50,
                    height: 50,
                    color: Colors.black),

              ],
            ),Column(mainAxisAlignment:MainAxisAlignment.center ,
              children: [
                Container(width: 50,
                  height: 50,
                  color: Colors.black,

                ),Container(width: 50,
                  height: 50,
                  color: Colors.white,

                ),Container(width: 50,
                    height: 50,
                    color: Colors.black),
                Container(width: 50,
                  height: 50,
                  color: Colors.white,),
                Container(width: 50,
                    height: 50,
                    color: Colors.black),
                Container(width: 50,
                    height: 50,
                    color: Colors.white),
                Container(width: 50,
                    height: 50,
                    color: Colors.black),
                Container(width: 50,
                    height: 50,
                    color: Colors.white),
              ],
            ),Column(mainAxisAlignment:MainAxisAlignment.center ,
              children: [
                Container(width: 50,
                  height: 50,
                  color: Colors.white,

                ),Container(width: 50,
                    height: 50,
                    color: Colors.black),
                Container(width: 50,
                  height: 50,
                  color: Colors.white,),
                Container(width: 50,
                    height: 50,
                    color: Colors.black),
                Container(width: 50,
                    height: 50,
                    color: Colors.white),
                Container(width: 50,
                    height: 50,
                    color: Colors.black),
                Container(width: 50,
                    height: 50,
                    color: Colors.white),
                Container(width: 50,
                    height: 50,
                    color: Colors.black),
              ],
            )
          ],
        ),
      ),
    );
  }
}
